import random

countries_and_capitals = [
    ("Afghanistan", "Kabul"),
    ("Albania", "Tirana"),
    ("Algeria", "Algiers"),
    ("Andorra", "Andorra la Vella"),
    ("Angola", "Luanda"),
    ("Antigua and Barbuda", "Saint John's"),
    ("Argentina", "Buenos Aires"),
    ("Armenia", "Yerevan"),
    ("Australia", "Canberra"),
    ("Austria", "Vienna"),
    ("Azerbaijan", "Baku"),
    ("Bahamas", "Nassau"),
    ("Bahrain", "Manama"),
    ("Bangladesh", "Dhaka"),
    ("Barbados", "Bridgetown"),
    ("Belarus", "Minsk"),
    ("Belgium", "Brussels"),
    ("Belize", "Belmopan"),
    ("Benin", "Porto-Novo"),
    ("Bhutan", "Thimphu"),
    ("Bolivia", "Sucre"),
    ("Bosnia and Herzegovina", "Sarajevo"),
    ("Botswana", "Gaborone"),
    ("Brazil", "Brasilia"),
    ("Brunei", "Bandar Seri Begawan"),
    ("Bulgaria", "Sofia"),
    ("Burkina Faso", "Ouagadougou"),
    ("Burundi", "Gitega"),
    ("Cabo Verde", "Praia"),
    ("Cambodia", "Phnom Penh"),
    ("Cameroon", "Yaounde"),
    ("Canada", "Ottawa"),
    ("Central African Republic", "Bangui"),
    ("Chad", "N'Djamena"),
    ("Chile", "Santiago"),
    ("China", "Beijing"),
    ("Colombia", "Bogota"),
    ("Comoros", "Moroni"),
    ("Congo", "Brazzaville"),
    ("Costa Rica", "San Jose"),
    ("Croatia", "Zagreb"),
    ("Cuba", "Havana"),
    ("Cyprus", "Nicosia"),
    ("Czech Republic", "Prague"),
    ("Democratic Republic of the Congo", "Kinshasa"),
    ("Denmark", "Copenhagen"),
    ("Djibouti", "Djibouti"),
    ("Dominica", "Roseau"),
    ("Dominican Republic", "Santo Domingo"),
    ("Ecuador", "Quito"),
    ("Egypt", "Cairo"),
    ("El Salvador", "San Salvador"),
    ("Equatorial Guinea", "Malabo"),
    ("Eritrea", "Asmara"),
    ("Estonia", "Tallinn"),
    ("Eswatini", "Mbabane"),
    ("Ethiopia", "Addis Ababa"),
    ("Fiji", "Suva"),
    ("Finland", "Helsinki"),
    ("France", "Paris"),
    ("Gabon", "Libreville"),
    ("Gambia", "Banjul"),
    ("Georgia", "Tbilisi"),
    ("Germany", "Berlin"),
    ("Ghana", "Accra"),
    ("Greece", "Athens"),
    ("Grenada", "Saint George's"),
    ("Guatemala", "Guatemala City"),
    ("Guinea", "Conakry"),
    ("Guinea-Bissau", "Bissau"),
    ("Guyana", "Georgetown"),
    ("Haiti", "Port-au-Prince"),
    ("Honduras", "Tegucigalpa"),
    ("Hungary", "Budapest"),
    ("Iceland", "Reykjavik"),
    ("India", "New Delhi"),
    ("Indonesia", "Jakarta"),
    ("Iran", "Tehran"),
    ("Iraq", "Baghdad"),
    ("Ireland", "Dublin"),
    ("Israel", "Jerusalem"),
    ("Italy", "Rome"),
    ("Ivory Coast", "Yamoussoukro"),
    ("Jamaica", "Kingston"),
    ("Japan", "Tokyo"),
    ("Jordan", "Amman"),
    ("Kazakhstan", "Astana"),
    ("Kenya", "Nairobi"),
    ("Kiribati", "South Tarawa"),
    ("Kuwait", "Kuwait City"),
    ("Kyrgyzstan", "Bishkek"),
    ("Laos", "Vientiane"),
    ("Latvia", "Riga"),
    ("Lebanon", "Beirut"),
    ("Lesotho", "Maseru"),
    ("Liberia", "Monrovia"),
    ("Libya", "Tripoli"),
    ("Liechtenstein", "Vaduz"),
    ("Lithuania", "Vilnius"),
    ("Luxembourg", "Luxembourg"),
    ("Madagascar", "Antananarivo"),
    ("Malawi", "Lilongwe"),
    ("Malaysia", "Kuala Lumpur"),
    ("Maldives", "Male"),
    ("Mali", "Bamako"),
    ("Malta", "Valletta"),
    ("Marshall Islands", "Majuro"),
    ("Mauritania", "Nouakchott"),
    ("Mauritius", "Port Louis"),
    ("Mexico", "Mexico City"),
    ("Micronesia", "Palikir"),
    ("Moldova", "Chisinau"),
    ("Monaco", "Monaco"),
    ("Mongolia", "Ulaanbaatar"),
    ("Montenegro", "Podgorica"),
    ("Morocco", "Rabat"),
    ("Mozambique", "Maputo"),
    ("Myanmar", "Naypyidaw"),
    ("Namibia", "Windhoek"),
    ("Nauru", "Yaren"),
    ("Nepal", "Kathmandu"),
    ("Netherlands", "Amsterdam"),
    ("New Zealand", "Wellington"),
    ("Nicaragua", "Managua"),
    ("Niger", "Niamey"),
    ("Nigeria", "Abuja"),
    ("North Korea", "Pyongyang"),
    ("North Macedonia", "Skopje"),
    ("Norway", "Oslo"),
    ("Oman", "Muscat"),
    ("Pakistan", "Islamabad"),
    ("Palau", "Ngerulmud"),
    ("Palestine", "East Jerusalem"),
    ("Panama", "Panama City"),
    ("Papua New Guinea", "Port Moresby"),
    ("Paraguay", "Asuncion"),
    ("Peru", "Lima"),
    ("Philippines", "Manila"),
    ("Poland", "Warsaw"),
    ("Portugal", "Lisbon"),
    ("Qatar", "Doha"),
    ("Romania", "Bucharest"),
    ("Russia", "Moscow"),
    ("Rwanda", "Kigali"),
    ("Saint Kitts and Nevis", "Basseterre"),
    ("Saint Lucia", "Castries"),
    ("Saint Vincent and the Grenadines", "Kingstown"),
    ("Samoa", "Apia"),
    ("San Marino", "San Marino"),
    ("Sao Tome and Principe", "Sao Tome"),
    ("Saudi Arabia", "Riyadh"),
    ("Senegal", "Dakar"),
    ("Serbia", "Belgrade"),
    ("Seychelles", "Victoria"),
    ("Sierra Leone", "Freetown"),
    ("Singapore", "Singapore"),
    ("Slovakia", "Bratislava"),
    ("Slovenia", "Ljubljana"),
    ("Solomon Islands", "Honiara"),
    ("Somalia", "Mogadishu"),
    ("South Africa", "Pretoria"),
    ("South Korea", "Seoul"),
    ("South Sudan", "Juba"),
    ("Spain", "Madrid"),
    ("Sri Lanka", "Sri Jayawardenepura Kotte"),
    ("Sudan", "Khartoum"),
    ("Suriname", "Paramaribo"),
    ("Sweden", "Stockholm"),
    ("Switzerland", "Bern"),
    ("Syria", "Damascus"),
    ("Taiwan", "Taipei"),
    ("Tajikistan", "Dushanbe"),
    ("Tanzania", "Dodoma"),
    ("Thailand", "Bangkok"),
    ("Timor-Leste", "Dili"),
    ("Togo", "Lome"),
    ("Tonga", "Nuku'alofa"),
    ("Trinidad and Tobago", "Port of Spain"),
    ("Tunisia", "Tunis"),
    ("Turkey", "Ankara"),
    ("Turkmenistan", "Ashgabat"),
    ("Tuvalu", "Funafuti"),
    ("Uganda", "Kampala"),
    ("Ukraine", "Kyiv"),
    ("United Arab Emirates", "Abu Dhabi"),
    ("United Kingdom", "London"),
    ("United States", "Washington, D.C."),
    ("Uruguay", "Montevideo"),
    ("Uzbekistan", "Tashkent"),
    ("Vanuatu", "Port Vila"),
    ("Vatican City", "Vatican City"),
    ("Venezuela", "Caracas"),
    ("Vietnam", "Hanoi"),
    ("Yemen", "Sanaa"),
    ("Zambia", "Lusaka"),
    ("Zimbabwe", "Harare"),
]


def play() -> None:
    score: int = 0
    questions_answered: int = 0

    country, capital = random.choice(countries_and_capitals)

    while True:
        guess: str = input(f"What is the capital of {country}: ")

        if guess.lower().strip() == "exit":
            print("Thank you for playing.")
            print(f"Your final score is {score}")
            if questions_answered > 0:
                accuracy = (score / questions_answered) * 100
                print(f"You have successfully answered {accuracy:.1f}% of the questions.")
            else:
                print("You didn't answer any questions.")
            break

        questions_answered += 1

        if guess.lower().strip() == capital.lower():
            score += 1
            print(f"Correct! Your score is {score}")
        else:
            print(f"Incorrect! The correct answer was {capital}.")

        country, capital = random.choice(countries_and_capitals)


if __name__ == "__main__":
    play()
